config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "posts#index"
  resources :posts

  get 'up', to: "healths#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :picture

  validates :title, :author, :content, presence: true
  validates :title, :author, length: {minimum: 2}
  validates :title, :author, length: {maximum: 50}
  validates :content, length: {minimum: 50}
  validates :content, length: {maximum: 2000}
  validates :picture, attached: true, size: { less_than: 100.megabytes , message: 'is too large' }, content_type: [:png, :jpg, :jpeg]

  def title
    self[:title]
  end
  def author
    self[:author]
  end
  def content
    self[:content]
  end
  def get_picture_url
    Rails.application.routes.url_helpers.url_for(picture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :set_timezone

  def set_locale
    I18n.locale = :en
  end

  def set_timezone
    Time.zone = "Europe/Paris"
  end

end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  def show
    render plain: "OK"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_posts, except: [:new, :create]
  before_action :get_post, only: [:edit, :update, :show, :destroy]

  def index; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash.notice = I18n.t("web.posts.create.success")
      redirect_to root_url
    else
      flash.alert = I18n.t("web.posts.create.error")
      render "posts/new"
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash.notice = I18n.t("web.posts.update.success")
      redirect_to root_url
    else
      flash.alert = I18n.t("web.posts.update.error")
      render "posts/edit"
    end
  end

  def show; end

  def destroy
    if @post.destroy
      flash.notice = I18n.t("web.posts.destroy.success")
    else
      flash.alert = I18n.t("web.posts.destroy.error")
    end
    redirect_to root_url
  end

  private
  def get_posts
    @posts = Post.all
  end

  def get_post
    @post = @posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :author, :content, :picture, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_active_class(controller, action)
    return "active" if controller_path == controller && action == action_name
    ""
  end
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Blog Ror</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <!-- START Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= root_url %>">Blog Test</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link <%= get_active_class("posts", "index") %>" aria-current="page" href="<%= root_url %>"><%= t("web.posts.index.page_title") %></a>
              <a class="nav-link <%= get_active_class("posts", "new") %>" href="<%= new_post_url %>"><%= t("web.posts.new.page_title") %></a>
            </div>
          </div>
        </div>
      </nav>
      <!-- END Navigation -->
    </header>

    <%= render partial: "layouts/partials/alerts" %>
    <%= yield %>


    <%= render partial: "layouts/partials/confirmation_modal" %>
  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
<% if !flash.now[:alert].blank? || !flash.notice.blank? %>
  <div class="container mt-5">
    <div class="row">
      <div class="col-12">
        <% unless flash.now[:alert].blank? %>
          <div class="alert alert-danger">
            <h4 class="alert-heading">Error saving!</h4>
            <p class="mb-0"><%= flash.now[:alert] %></p>
          </div>
        <% end %>
        <% unless flash.notice.blank? %>
          <div class="alert alert-success">
            <h4 class="alert-heading">Post saved!</h4>
            <p class="mb-0"><%= flash.notice %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/partials/_confirmation_modal.html.erb
<!-- START Confirmation Modal -->
<div class="modal fade" id="confirmModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("common.delete_confirm.confirm_action") %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p id="confirm_text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><%= t("common.cancel") %></button>
        <a href="" id="confirm_btn" class="btn btn-outline-danger"><%= t("common.delete") %></a>
      </div>
    </div>
  </div>
</div>
<!-- END Confirmation Modal -->

app/views/posts/_form.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div class="col-12">
      <%= form_for @post, multipart: true, local: true, data: { turbo: false } do |f| %>
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <div class="mb-3">
                  <%= f.label :title, class: "form-label" %>
                  <%= f.text_field :title,
                                   class: "form-control",
                                   required: true,
                                   minlength: 2,
                                   maxlength: 500,
                                   placeholder: "Post Title"
                  %>
                </div>
              </div>
              <div class="col-6">
                <div class="mb-3">
                  <%= f.label :author, class: "form-label" %>
                  <%= f.text_field :author,
                                   class: "form-control",
                                   required: true,
                                   minlength: 2,
                                   maxlength: 50,
                                   placeholder: "Name"
                  %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-6">
                <div class="mb-3">
                  <%= f.label :picture, class: "form-label" %>
                  <%= f.file_field :picture, class: "form-control", accept: "image/png, image/jpeg, image/jpg", required: !@post.persisted? %>
                </div>
              </div>
              <div class="col-6">
                <div class="mb-3">
                  <%= f.label :email, class: "form-label" %>
                  <%= f.email_field :email,
                                   class: "form-control",
                                   required: true,
                                   placeholder: "Email"
                  %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <div class="mb-3">
                  <%= f.label :content, class: "form-label" %>
                  <%= f.text_area :content, class: "form-control", rows: 5, required: true, minlength: 50 %>
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer text-end">
            <button class="btn btn-success"><i class="bi bi-save me-2"></i><%= t("common.save") %></button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-12 col-sm-6 col-lg-4 mb-3">
  <div class="card position-relative">
    <div class="ratio ratio-16x9">
      <img src="<%= post.get_picture_url %>" class="card-img-top object-fit-cover" alt="">
    </div>

    <div class="position-absolute top-0 end-0 p-2">
      <a href="#confirmModal" class="btn btn-danger js-delete" data-bs-toggle="modal" data-confirm="<%= t("common.delete_confirm.confirm_action_description") %>" data-url="<%= post_url(post) %>" data-method="delete"><i class="bi bi-trash"></i></a>
    </div>

    <div class="card-body">
      <h5 class="card-title mb-0 text-truncate"><%= post.title %></h5>
      <p class="small text-truncate"><%= post.author %></p>

      <p class="card-text text-truncate-2"><%= post.content %></p>

      <div class="row justify-space-between">
        <div class="col">
          <a href="<%= post_url(post) %>" class="btn btn-primary"><%= t("common.show") %></a>
        </div>
        <div class="col text-end">
          <a href="<%= edit_post_url(post) %>" class="btn btn-success"><i class="bi bi-pencil-square me-2"></i><%= t("common.edit") %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "posts/form" %>

app/views/posts/index.html.erb
<div class="container pt-5">
  <div class="row">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render partial: "posts/form" %>

app/views/posts/show.html.erb
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active ratio ratio-16x9">
      <img src="<%= @post.get_picture_url %>" class="d-block w-100" alt="">
      <div class="carousel-caption bg-dark-opacity-center">
        <div class="d-flex align-items-center h-100 justify-content-center">
          <div>
            <span class="display-1"><%= @post.title %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container pt-5">
  <div class="row mb-4">
    <div class="col-10">
      <h1 class="mb-0"><%= @post.title %></h1>
      <p class="mb-0"><span class="fs-5">By <%= @post.author %></span> <span class="small"> <%= l(@post.created_at, format: :long) %></span></p>
    </div>
    <div class="col-2 text-end">
      <a href="#confirmModal" class="btn btn-danger js-delete" data-bs-toggle="modal" data-confirm="<%= t("common.delete_confirm.confirm_action_description") %>" data-url="<%= post_url(@post) %>" data-method="delete"><i class="bi bi-trash"></i></a>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <% @post.content.split("\n").each do |p| %>
        <p><%= p %></p>
      <% end %>
    </div>
  </div>
</div>